controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Article;
use app\models\Rating;
use Yii;
use yii\data\Sort;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\data\ActiveDataProvider;
class SiteController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }



    public function actionIndex(){

        $dataProvider = new ActiveDataProvider([
            'query' =>  Article::find()->asArray()->with('rating'),
            'pagination' => ['pageSize'=>100]
        ]);

        $sort = new Sort([
            'attributes' => [
                'data' => [
                    'asc' => ['data' => SORT_ASC],
                    'desc' => ['data' => SORT_DESC],
                    'default' => SORT_ASC,
                    'label' => 'Дате',
                ],
                'rate_bad_count' => [
                    'asc' => ['rate_bad_count' => SORT_ASC],
                    'desc' => ['rate_bad_count' => SORT_DESC],
                    'label' => 'Не понравилось',
                ],
                'rate_good_count' => [
                    'asc' => ['rate_good_count' => SORT_ASC],
                    'desc' => ['rate_good_count' => SORT_DESC],
                    'label' => 'Хорошо',
                ],
                'rate_excellent_count' => [
                    'asc' => ['rate_excellent_count' => SORT_ASC],
                    'desc' => ['rate_excellent_count' => SORT_DESC],
                    'label' => 'Отлично',
                ],
            ],
        ]);

        return $this->render('index', compact('dataProvider', 'sort'));
    }

    public function actionView($id){
        $article = Article::findOne($id);
        if(empty($article)){
            throw new \yii\web\HttpException(404, 'Данной страницы не существует.');
        }
        $q = "SELECT rate, count(rate) as `count` FROM `rating` where article_id = $id GROUP by rate";
        $rating = Rating::findBySql($q)->asArray()->all();



        $rating_model = new Rating();
        $rating_model->rate = 1;
        if( $rating_model->load(Yii::$app->request->post())){

            if($rating_model->save()){

                $article->rate_bad_count = $rating[0]['count']; // оценка 'Не понравилось'.
                $article->rate_good_count = $rating[1]['count']; // оценка 'Хорошо'.
                $article->rate_excellent_count = $rating[2]['count']; // оценка 'Отлично'.
                $article->save();

                $rating_model->article_id = $article->id;
                $rating_model->user_id = Yii::$app->user->identity->id;
                $rating_model->save();

                Yii::$app->session->setFlash('success', 'Оценка добавлена');
                return $this->redirect(Yii::$app->request->referrer);
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
        }

       return $this->render('view', compact('article', 'rating', 'rating_model'));
    }

    public function actionAdd(){

        $model = new Article();

        if( $model->load(Yii::$app->request->post())){

            $model->user_id = Yii::$app->user->identity->id;
            $model->save();

            if($model->save()){

                Yii::$app->session->setFlash('success', 'Публикацию добавлено');
                return $this->redirect(Yii::$app->request->referrer);
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка при добавление');
            }
        }

        return $this->render('add', compact('model'));
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    
}

views/site/_post.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;

$sum = [];
?>
<div class="post">



    <div class="article col-lg-12">
        <div class="title"><h3><?= Html::encode($model['title']) ?></h3></div>
        <div class="content"> <?= HtmlPurifier::process($model['content']) ?></div>

        <p><a href="<?= \yii\helpers\Url::to(['site/view', 'id' => $model['id']]) ?>">Подробнее</a></p>
    </div>

</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/add.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

?>
<div class="addArticle">
    <h2>Добавить публикацию</h2>
    <?php if(Yii::$app->user->isGuest): ?>
        <h3>Ввойдите для добавления публикации.</h3>
    <?php endif; ?>
    <?php if(!Yii::$app->user->isGuest): ?>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'content')->textarea(['rows' => 5]) ?>

    <?= Html::submitButton('Добавить', ['class' => 'btn btn-success']) ?>

    <?php ActiveForm::end(); ?>
    <?php endif; ?>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\widgets\ListView;

$this->title = 'Все публикации';

?>
<div class="site-index container">
    <h1>Все публикации</h1>

        <h5>Сортировать по: <?= $sort->link('data') ?></h5>
        <h5>Сортировать по оценки: <?= $sort->link('rate_bad_count') ?> | <?= $sort->link('rate_good_count') ?> |
            <?= $sort->link('rate_excellent_count') ?> </h5>
        <?php
        echo ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_post',
        ]);
        ?>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use budyaga\users\components\AuthorizationWidget;
$this->title = 'Логин';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login container">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= AuthorizationWidget::widget() ?>

</div>

views/site/view.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = $article['title'];
?>

<!-- Получение процентов для рейтинга-->
<?php $sum = $rating[0]['count'] + $rating[1]['count'] + $rating[2]['count'] ?>
<?php if ( !empty($rating[0]['count']) && !empty($rating[1]['count']) && !empty($rating[2]['count']) ): ?>

<?php $rate0 = round($rating[0]['count'] * 100 /  $sum); ?>
<?php $rate1 = round($rating[1]['count'] * 100 /  $sum); ?>
<?php $rate2 = round($rating[2]['count'] * 100 /  $sum); ?>
<?php //debug($rating[0]['count']) ?>
<?php endif; ?>
<div class="site-index ">
        <div class="article col-lg-12">
            <div class="title"><h2><?= $article['title']; ?></h2></div>
            <div class="content"> <?= $article['content']; ?></div>

            <?php if( Yii::$app->user->isGuest) : ?>

                <br/>
                <h5>Ввойдите что-бы оценить запись</h5>
            <? endif; ?>
            <?php if(!Yii::$app->user->isGuest): ?>

            <?php if($article['user_id'] != Yii::$app->user->identity->id  ): ?>
                    <!-- Форма рейтингу-->
                <?php $form = ActiveForm::begin(); ?>
                <?= $form->field($rating_model, 'rate')->radioList([0 => 'Не понравилось', 1 => 'Хорошо', 2 => 'Отлично']) ?>
                <?= Html::submitButton('Оценить', ['class' => 'btn btn-success']) ?>
                <?php ActiveForm::end(); ?>
            <?php elseif($article['user_id']  == Yii::$app->user->identity->id ): ?>
                    <h5>Автор статьи не может голосовать</h5>
                <?php endif; ?>

                <!-- Оценка рейтинга публикации-->
                <?php if( !empty($rating[0]['count']) && !empty($rating[1]['count']) && !empty($rating[2]['count'])): ?>
                <h5>
                    <?php if( empty($rating[0]['count']) ) echo 0; else echo $rating[0]['count']; ?> пользователей поставило оценку 'Не понравилось',
                    <?php if( empty($rating[1]['count']) ) echo 0; else echo $rating[1]['count']; ?>  пользователя - 'Хорошо',
                    <?php if( empty($rating[2]['count']) ) echo 0; else echo $rating[2]['count']; ?>  пользователей 'Отлично'.
                </h5>
                <?php else: ?>
                    <h5>Рейтинг появится когда все варианты будут иметь минимум один голос.</h5>
                <?php endif; ?>
                <?php if( ($rate0 > $rate1) && ($rate0 > $rate2) ): ?>
                    <h5>Итоговая оценка: 'Не понравилось' (<?= $rate0 ?> %)</h5>
                <?php endif; ?>
                <?php if( ($rate1 > $rate2) && ($rate1 > $rate0) ): ?>
                    <h5>Итоговая оценка: 'Хорошо' (<?= $rate1 ?> %)</h5>
                <?php endif; ?>

                <?php if( ($rate2 > $rate1) && ($rate2 > $rate0) ): ?>
                    <h5>Итоговая оценка: 'Отлично' (<?= $rate2 ?> %)</h5>
                <?php endif; ?>

            <? endif; ?>
        </div>



</div>